Medellín, Colombia 25 de Abril de 2026
<table style="border: none; border-collapse: collapse; width: 100%;">
    <tr style="border: none;">
        <td style="border: none; width: 120px; vertical-align: middle;">
            <img src="img/logo.png" style="width: 100px;"/>
        </td>
        <td style="border: none; vertical-align: middle;">
            <div style="color:#BA352C; font-size: 32px; font-weight: bold; line-height: 1.2;">
                Universidad Autónoma Latinoamericana
            </div>
            <div style="color:#FC9C28; font-size: 26px; font-weight: bold; line-height: 1.2;">
                Especialización, Analítica de datos - Grupo 2
            </div>
        </td>
    </tr>
</table>

<span style="font-size: 18px;">Entregable Final de la Asignatura: Principios analíticos para la ciencia de datos</span>

<span style="font-size: 24px; font-weight: bold;">Integrantes</span>

- Evelin Dahiana Franco Campiño
- Kevin Mateo Jiménez Guisao
- Nicolle Gaviria Mejía

</br>

***

<div>
    <span style=" font-size: xxx-large; font-weight: bold;"> Análisis Exploratorio de Datos (EDA) </span>
</div>
<div >
    <span style=" font-size: xx-large; font-weight: bold;">Salud mental estudiantil y síndrome de burnout </span>
</div>

## 1. 📄 Introducción 

<p>
    El Conjunto de Datos sobre Salud Mental y Agotamiento Estudiantil (150k filas, 20 características) es una base de datos a gran escala diseñada para analizar y predecir los niveles de burnout (agotamiento) estudiantil basándose en factores académicos, psicológicos y de estilo de vida. 
</p>

> Este conjunto de datos contiene 150,000 registros de estudiantes con una combinación de variables numéricas y categóricas, lo que lo hace ideal para tareas de aprendizaje automático (machine learning), clasificación y análisis de datos.

## 2. 🧮 Conjunto de Datos
**Características:**
- Demografía: Edad, género, carrera y año académico.

- Indicadores académicos: Promedio general (CGPA), asistencia y horas de estudio.

- Puntajes psicológicos: Niveles de ansiedad, depresión y estrés.

- Factores de estilo de vida: Horas de sueño, actividad física y tiempo frente a la pantalla.

- Indicadores de estrés social y financiero.

- Variable objetivo: `burnout_level` (nivel de agotamiento).

<table style="width: 500px; margin-left: 0; margin-right: auto;">
    <thead>
        <tr style="background-color: #BA352C; color: white;">
            <th style="padding: 10px; text-align: left; border: 1px solid #ddd;">Información</th>
            <th style="padding: 10px; text-align: left; border: 1px solid #ddd;">Detalle</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="background-color: #FC9C2833; font-weight: bold; padding: 8px; border: 1px solid #ddd; width: 150px;">Fuente</td>
            <td style="padding: 8px; border: 1px solid #ddd; ; width: 350px;">
                <a href="https://www.kaggle.com/datasets/sehaj1104/student-mental-health-and-burnout-dataset/data" target="_blank">Kaggle - Dataset Link</a>
            </td>
        </tr>
        <tr>
            <td style="background-color: #FC9C2833; font-weight: bold; padding: 8px; border: 1px solid #ddd; width: 150px;">Nombre del dataset</td>
            <td style="padding: 8px; border: 1px solid #ddd; width: 350px;">Student Mental Health and Burnout Dataset</td>
        </tr>
        <tr>
            <td style="background-color: #FC9C2833; font-weight: bold; padding: 8px; border: 1px solid #ddd; width: 150px;">Propietario</td>
            <td style="padding: 8px; border: 1px solid #ddd; width: 350px;">Mansehaj Preet</td>
        </tr>
        <tr>
            <td style="background-color: #FC9C2833; font-weight: bold; padding: 8px; border: 1px solid #ddd; width: 150px;">Tipo de Origen</td>
            <td style="padding: 8px; border: 1px solid #ddd; width: 350px;">Archivo CSV</td>
        </tr>
    </tbody>
</table>

### 2.1 Importación del conjunto de datos

In [1]:
from IPython.core.display import Markdown
from IPython.core.display_functions import display
import pandas as pd

# Cargar dataset
path = "data/datos.csv"
df_raw = pd.read_csv(path, sep=",", header="infer")

# Crear copia de trabajo
df = df_raw.copy()

# Total de filas
total_filas = len(df)
display(Markdown(f"Total de registros: {total_filas}"))
display(Markdown(f"#### **Muestra del conjunto de datos**"))
display(df.sample(n=10, ignore_index=True))

Total de registros: 150000

#### **Muestra del conjunto de datos**

,student_id,age,gender,course,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,financial_stress_score,social_support_score,physical_activity_hours,sleep_quality,attendance_percentage,cgpa,internet_quality,burnout_level
0,84921110,17.0,Female,BTech,3rd,8.6,8.3,11.2,Low,1.0,5.0,3.0,9,1.0,1.7,Average,92.2,9.93,Good,Medium
1,83838111,23.0,Male,BTech,2nd,4.6,4.8,11.7,High,9.0,6.0,7.0,8,3.0,0.9,Poor,86.1,6.49,Average,Medium
2,47404764,24.0,Female,BTech,4th,5.7,6.9,5.2,High,8.0,6.0,6.0,5,8.0,1.1,Average,50.9,6.63,Average,Medium
3,47972352,24.0,Female,BCA,2nd,6.9,8.8,1.5,Medium,5.0,4.0,3.0,4,2.0,0.4,Good,89.5,9.17,Average,Low
4,78889069,17.0,Other,BSc,2nd,2.2,7.0,1.7,Medium,10.0,9.0,5.0,6,8.0,1.3,Good,52.4,7.61,Good,Medium
5,96928982,17.0,Male,MBA,1st,8.0,6.4,11.8,High,5.0,5.0,6.0,7,5.0,0.9,Good,61.7,8.98,Average,Low
6,27843381,18.0,Male,BSc,4th,8.2,7.0,11.6,High,6.0,4.0,7.0,1,9.0,1.1,Poor,61.4,5.49,Good,High
7,27078636,19.0,Male,BSc,3rd,2.1,6.0,8.5,Low,10.0,9.0,9.0,5,8.0,0.1,Average,65.1,9.99,Poor,Medium
8,86407762,24.0,Female,MBA,4th,5.1,8.5,10.3,Low,5.0,8.0,9.0,6,10.0,1.1,Average,61.4,5.00,Poor,High
9,20606171,25.0,Male,BBA,2nd,1.2,6.3,7.6,Medium,7.0,4.0,10.0,9,1.0,1.3,Average,88.2,5.71,Good,Low

### 2.2 Información de las columnas del conjunto de datos

> Se creará un dataset nuevo que explique cada columna, cuántos valores no vacíos contiene todo el conjunto y qué tipo de datos interpreta el sistema según su contenido.

In [2]:
# Crear info_df para presentar

info_df = pd.DataFrame({
    'Columna': df.columns,
    'No Nulos': df.count().values,
    'Tipo de Dato': df.dtypes.values
})

display(info_df)

                    Columna  No Nulos Tipo de Dato
0                student_id    150000        int64
1                       age    149999      float64
2                    gender    149999          str
3                    course    149997          str
4                      year    149998          str
5         daily_study_hours    149996      float64
6         daily_sleep_hours    149999      float64
7         screen_time_hours    150000      float64
8              stress_level    149997          str
9             anxiety_score    149998      float64
10         depression_score    149999      float64
11  academic_pressure_score    149999      float64
12   financial_stress_score    150000        int64
13     social_support_score    149999      float64
14  physical_activity_hours    149999      float64
15            sleep_quality    150000          str
16    attendance_percentage    149997      float64
17                     cgpa    149999      float64
18         internet_quality    149998          str
19            burnout_level    149998          str

### 2.3 📙 Diccionario de Datos

<table style="width: 1200px; margin-left: 0; margin-right: auto;">
    <thead style="background-color: #352cba80">
        <tr>
            <td><b>Columna</b></td>
            <td><b>Formato</b></td>
            <td><b>Descripción</b></td>
            <td><b>Ejemplos Reales</b></td>
        </tr>        
    </thead>
    <tbody>
        <tr>
            <td><b> student_id</b></td>
            <td>Entero</td>
            <td>Identificador único para cada estudiante.</td>
            <td>73698903, 36386454 (Rango: 10000510 - 99999584)</td>
        </tr>
        <tr>
            <td><b>age</b></td>
            <td>Flotante</td>
            <td>Edad del estudiante.</td>
            <td>17.0, 20.0, 25.0</td>
        </tr>
        <tr>
            <td><b>gender</b></td>
            <td>Texto</td>
            <td>Género del estudiante.</td>
            <td>Male, Female, Other</td>
        </tr>
        <tr>
            <td><b>course</b></td>
            <td>Texto</td>
            <td>
                Programa académico matriculado:<br>
                • <b>BTech:</b> Licenciatura en Tecnología<br>
                • <b>BSc:</b> Licenciatura en Ciencias<br>
                • <b>BCA:</b> Licenciatura en Aplicaciones Informáticas<br>
                • <b>BBA:</b> Licenciatura en Administración de Empresas<br>
                • <b>MCA:</b> Maestría en Aplicaciones Informáticas<br>
                • <b>MBA:</b> Maestría en Administración de Empresas
            </td>
            <td>BTech, BCA, BSc, MBA, MCA, BBA</td>
        </tr>
        <tr>
            <td><b>year</b></td>
            <td>Texto</td>
            <td>Año de estudio del estudiante.</td>
            <td>1st, 2nd, 3rd, 4th</td>
        </tr>
        <tr>
            <td><b>daily_study_hours</b></td>
            <td>Flotante</td>
            <td>Tiempo promedio diario de estudio.</td>
            <td>4.3, 1.4 (Rango: 1.0 - 10.0)</td>
        </tr>
        <tr>
            <td><b>daily_sleep_hours</b></td>
            <td>Flotante</td>
            <td>Duración promedio diaria de sueño.</td>
            <td>6.8, 4.7 (Rango: 4.0 - 9.0)</td>
        </tr>
        <tr>
            <td><b>screen_time_hours</b></td>
            <td>Flotante</td>
            <td>Tiempo diario de exposición a pantallas.</td>
            <td>6.1, 3.0 (Rango: 1.0 - 12.0)</td>
        </tr>
        <tr>
            <td><b>stress_level</b></td>
            <td>Texto</td>
            <td>Categoría de estrés autorreportada.</td>
            <td>High, Medium, Low</td>
        </tr>
        <tr>
            <td><b>anxiety_score</b></td>
            <td>Flotante</td>
            <td>Puntaje de ansiedad (escala 1–10).</td>
            <td>10.0, 2.0 (Rango: 1.0 - 10.0)</td>
        </tr>
        <tr>
            <td><b>depression_score</b></td>
            <td>Flotante</td>
            <td>Puntaje de depresión (escala 1-10).</td>
            <td>3.0, 10.0 (Rango: 1.0 - 10.0)</td>
        </tr>
        <tr>
            <td><b>academic_pressure_score</b></td>
            <td>Flotante</td>
            <td>Puntaje de presión académica (escala 1-10).</td>
            <td>4.0, 8.0 (Rango: 1.0 - 10.0)</td>
        </tr>
        <tr>
            <td><b>financial_stress_score</b></td>
            <td>Entero</td>
            <td>Puntaje de estrés financiero (escala 1-10).</td>
            <td>2, 5 (Rango: 1 - 10)</td>
        </tr>
        <tr>
            <td><b>social_support_score</b></td>
            <td>Flotante</td>
            <td>Puntaje de apoyo social (escala 1-10).</td>
            <td>6.0, 9.0 (Rango: 1.0 - 10.0)</td>
        </tr>
        <tr>
            <td><b>physical_activity_hours</b></td>
            <td>Flotante</td>
            <td>Horas diarias de actividad física.</td>
            <td>1.8, 1.9 (Rango: 0.0 - 2.0)</td>
        </tr>
        <tr>
            <td><b>sleep_quality</b></td>
            <td>Texto</td>
            <td>Calidad del sueño reportada.</td>
            <td>Good, Average, Poor</td>
        </tr>
        <tr>
            <td><b>attendance_percentage</b></td>
            <td>Flotante</td>
            <td>Porcentaje de asistencia a clases.</td>
            <td>66.5, 55.8 (Rango: 50.0 - 100.0)</td>
        </tr>
        <tr>
            <td><b>cgpa</b></td>
            <td>Flotante</td>
            <td>Promedio de calificaciones acumulado (CGPA).</td>
            <td>9.63, 6.04 (Rango: 4.0 - 10.0)</td>
        </tr>
        <tr>
            <td><b>internet_quality</b></td>
            <td>Texto</td>
            <td>Calidad de la conexión a internet.</td>
            <td>Good, Average, Poor</td>
        </tr>
        <tr>
            <td><b>burnout_level</b></td>
            <td>Texto</td>
            <td>Nivel de agotamiento (burnout).</td>
            <td>High, Medium, Low</td>
        </tr>
    </tbody>
</table>

## 3. 📈 Resumen Estadístico

> Antes de proceder con el análisis, se debe retirar
 del radar la columna `student_id` dado que esta representa un identificador por fila y no sería productiva ninguna función de agregación referente a este campo

In [3]:
# Se crea un nuevo dataset sin la columna student_id

df_stats = df.drop("student_id", axis=1)

# Se usa la función describe para sacar el resumen estadístico general

display(df_stats.describe())

,age,daily_study_hours,daily_sleep_hours,screen_time_hours,anxiety_score,depression_score,academic_pressure_score,financial_stress_score,social_support_score,physical_activity_hours,attendance_percentage,cgpa
count,149999.000000,149996.000000,149999.000000,150000.000000,149998.000000,149999.000000,149999.000000,150000.000000,149999.000000,149999.000000,149997.000000,149999.000000
mean,21.000387,5.507853,6.499345,6.502819,5.493873,5.497357,5.507457,5.496027,5.516037,0.998120,75.009734,6.997391
std,2.581224,2.595616,1.443851,3.178948,2.872602,2.869031,2.875510,2.864698,2.870489,0.578865,14.409489,1.732186
min,17.000000,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,50.000000,4.000000
25%,19.000000,3.300000,5.200000,3.700000,3.000000,3.000000,3.000000,3.000000,3.000000,0.500000,62.500000,5.500000
50%,21.000000,5.500000,6.500000,6.500000,5.000000,5.000000,6.000000,6.000000,6.000000,1.000000,75.000000,6.990000
75%,23.000000,7.700000,7.700000,9.300000,8.000000,8.000000,8.000000,8.000000,8.000000,1.500000,87.500000,8.500000
max,25.000000,10.000000,9.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,100.000000,10.000000

## 4. ✅ Calidad de los datos

Antes de realizar un análisis exhaustivo de los datos, primero evaluaremos qué tan fiables son, revisando datos vacíos, valores improbables y valores duplicados.

### 4.1 Datos Vacíos

In [13]:
# 1. Calculamos la suma de nulos
nulos = df.isnull().sum()

# 2. Filtramos solo los que son mayores a cero
nulos_filtrados = nulos[nulos > 0]

# 3. Validamos si hay resultados para mostrar
if not nulos_filtrados.empty:
    # Convertimos a DataFrame y luego a markdown
    tabla_nulos_md = nulos_filtrados.to_frame(name="Valores Nulos").to_markdown()
    
    display(Markdown("### Columnas con Valores Nulos"))
    display(Markdown(tabla_nulos_md))
else:
    display(Markdown("### No hay valores nulos en el DataFrame 🎉"))

### Columnas con Valores Nulos

|                         |   Valores Nulos |
|:------------------------|----------------:|
| age                     |               1 |
| gender                  |               1 |
| course                  |               3 |
| year                    |               2 |
| daily_study_hours       |               4 |
| daily_sleep_hours       |               1 |
| stress_level            |               3 |
| anxiety_score           |               2 |
| depression_score        |               1 |
| academic_pressure_score |               1 |
| social_support_score    |               1 |
| physical_activity_hours |               1 |
| attendance_percentage   |               3 |
| cgpa                    |               1 |
| internet_quality        |               2 |
| burnout_level           |               2 |

In [16]:
# Filtramos el DataFrame para obtener solo las filas con algún valor nulo
df_filas_nulas = df[df.isnull().any(axis=1)]
# Mostramos el mensaje superior
display(Markdown(f"**Mostrando {len(df_filas_nulas)} filas que contienen al menos un valor nulo:**"))
# Aplicamos el estilo para resaltar los nulos en amarillo y lo mostramos
display(df_filas_nulas.style.highlight_null(color='yellow'))

**Mostrando 13 filas que contienen al menos un valor nulo:**